
cara1():- write("    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n"),
          write("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n"),
          write(" XXXXXXXXXXXXXXXXXX         XXXXXXXX\n"),
          write("XXXXXXXXXXXXXXXX              XXXXXXX\n"),
          write("XXXXXXXXXXXXX                   XXXXX\n"),
          write(" XXX     _________ _________     XXX\n"),
          write("  XX    I  _xxxxx I xxxxx_  I    XX\n"),
          write(" ( X----I         I         I----X )\n"),
          write("( +I    I      00 I 00      I    I+ )\n"),
          write("X( I    I    __0  I  0__    I    I )X\n"),
          write("XX(I    I_________I_________I    I)XX\n"),
          write("XXXI            ( _ )            IXXX\n"),
          write("XXXI                             iXXX\n"),
          write("XXXX;                           ;XXXX\n"),
          write("XXXXX;_       |_______|       _;XXXXX\n"),
          write("XXXXXXX;                     ;XXXXXXX\n"),
          write("XXXXXXXX;                   ;XXXXXXXX\n"),
          write("XXXXXXXXX;                 ;XXXXXXXXXX\n"),
          write("XXXXXXXXXX;_______________;XXXXXXXXXX\n").
          
                                 
cara2():- write("          .#########.#######..\n"),
          write("          .#######################.\n"),
          write("        .############################.\n"),
          write("       .################################.\n"),
          write("      .#########,##,#####################.\n"),
          write("     .#########-#,'########## ############.\n"),
          write("    .######'#-##' # ##'### #. `####:#######.\n"),
          write("    #####:'# #'###,##' # # +#. `###:':######\n"),
          write("   .####,'###,##  ###  # # #`#. -####`######.\n"),
          write("  .####+.' ,'#  ##' #   # # #`#`.`#####::####\n"),
          write("  ####'    #  '##'  #   #_'# #.## `#######;##\n"),
          write("  #:##'      '       #   # ``..__# `#######:#\n"),
          write("  #:##'  .#######s.   #.  .s######.\`#####:##\n"),
          write("  #:##   .'______'''    '''_____''. `.#####:#\n"),
          write(" .#:##   ><'(##)'> )    ( <'(##)`><   `####;#\n"),
          write(" ##:##  , , -==-' '.    .` `-==- . |  ######'\n"),
          write(" #|-'| / /      ,  :    : ,       | ` :####:'\n"),
          write(" :#  |: '  '   /  .     .  .  `    `  |`####\n"),
          write(" #|  :|   /   '  '       `  |   . ,   :  #:#\n"),
          write(" #L. | | ,  /   `.-._ _.-.'   .  | |  : ) J##\n"),
          write("###| `  /  '                   |  : : |  /##\n"),
          write(" ## #|.:: '                     ` | | |'####\n"),
          write(" #####||  |                      :| ' ######\n"),
          write(" ######|:       |          |      :: /######\n"),
          write(" #######|``     |__________|   ,'|  /#######\n"),
          write(".# ######|  |        ___       / /' /#######\n"),
          write("# #'#####||  |     -     -    /  ,'|### #. #.\n"),
          write("`#  #####| '-.`             ' ,-'  |### #  #\n"),
          write("    #' `#|    '._         ,.-'     |#`#`#.\n"),
          write("         |       .'------' :       |#   #\n"),
          write("         |       :         :       |\n"),
          write("         |       :         :       |\n").
          
          
cara3():- write("             .g$$$Sbp.\n"),
          write("           .d$$$$SSS$$Sp.\n"),
          write("          dS$$$$SS$$$$$SSb. \n"),
          write("         :S$$$$$SSSS$$$$$SSb     \n"),
          write("         $S$$$$$$SS$SSSSSS$S;         \n"),
          write("        :$$$S$$SS^'^^''^TSSS:             \n"),
          write("        $$$S$$SP         T$SS;                \n"),
          write("       :$$$S$SP           $$SS                \n"),
          write("       $$$S$$$            :$$S;               \n"),
          write("      :$$$S$$;=-.     ,-=^.T$$Sb              \n"),
          write("      $$$SS$$.__.     .__. $S$$$b             \n"),
          write("    .d$$SS$$; ""       ""  :SSS$$;            \n"),
          write("   d$$SSS$$$               :S$$S$$            \n"),
          write("  :$$SS$$$$;      ._.      $$S$$$$            \n"),
          write("  $$SS$$$$S$b    .___.    d$$$S$$;            \n"),
          write("  :SSS$$S$S$$b   |.-.|   d$$$$S$P`.           \n"),
          write("   `^S$S$$SS$$b.  `-'  .'|^T$P^'             \n"),
          write("      TS^T$SSSP `.___.'   |             \n"),
          write("             :             `.   \n").


cara4():- write("                              _,aaddd8888888bbbaa,_\n"),
          write("                            ,d888888888888888888888b,\n"),
          write("                          ,d8888888888888888888888888b,\n"),
          write("                        ,d8888888888888888I888888888888,\n"),
          write("                       ,8888888888888888888I888888888888,\n"),
          write("                      ,888888888888888888888I888888888888,\n"),
          write("                     ,88888888888888888888888I888888888888,\n"),
          write("                    ,8888888888888888888888888I88888888888b\n"),
          write("                   ,888888888888888888888888888I88888888888,\n"),
          write("                   d888888888888888888888888888I888888888888\n"),
          write("                  ,888888888888888888888888888I8888888888888,\n"),
          write("                  d8888888888888''Y88888888P''Y8888888888888b\n"),
          write("                 ,8888888888888'  __`''''''   __`'''' `888888\n"),
          write("                 d8888888888888  `''''''     `''''''   888888\n"),
          write("                ,88888888888888    ggg, I  I   ,ggg    88888P\n"),
          write("               ,d88888888888888    `Y8P  I     88P'    88888'\n"),
          write("               d888888888888888          I            ,88888\n"),
          write("               8888888888888888         .f  .         d88888\n"),
          write("               8888888888888888,      | (a_a) |      ,888888\n"),
          write("               Y888888888888888b    |           |   ,8888888,\n"),
          write("               `8888888888888888      ,ad8a8ba,    ,88888888b\n"),
          write("                `888888888888888b      'Y888P'    ,8888888888\n"),
          write("                 `888888888888888b,              ,88888888888,\n"),
          write("                  `Y888888888888888b,          ,d888888888888b\n"),
          write("                  ,d88888888888888b`Yb_      _dP88888888888888\n"),
          write("               ,ad88888888888888888b `'YaaaaP'',88888888888888\n"),
          write("              d888888888888888888888,          d8888888888888P\n"),
          write("             d8888888888888888888888b          8888888888888P'\n"),
          write("             888888888888888888888888          888888888888P'\n"),
          write("             8888888PP'''''8888888888b,        Y8888888888P\n"),
          write("             Y88P''       d8888888888,'Ya,   ,aPY888888888I\n"),
          write("             ,8'          Y8888888888b  `'Y8P'' `888888888I\n"),
          write("             d'           `88888888888    |o|,   8888888888b,\n"),
          write("            ,P             888888888P'   ,d |b,  88888888888b,\n"),
          write("            d'             `Y88888P'    ,d|  |b, 888888888888b,\n"),
          write("           ,P                `''' 'b,   d'|  |`b 8888888888888b,\n"),
          write("           d'                       'b,,I | O| I,d8888888888888b\n"),
          write("           8                          'Y'  |  |`Y'Y8888888888888\n"),
          write("           8                               |  |    'Y8888888888P\n"),
          write("           8                  ,8            |  |     `'Y8888PP'\n").


cara5():- write("             .-""""--.\n"),
          write("           .'     )   '-.\n"),
          write("          /      (       `.\n"),
          write("         :        ;        \\n"),
          write("         ;        : ,---.   ;\n"),
          write("        :       .-'--'-.`. :\n"),
          write("        ;      |         | : ;\n"),
          write("       :      |           ; ::\n"),
          write("       ;     :            :  `.\n"),
          write("      :      ;=-.     ,-=^.|   .\n"),
          write("      ;   | :.__.     .__. ;|   ;\n"),
          write("    .'   |  ; ""       ""  : `.  ;\n"),
          write("   ;   .'  :               :.    :\n"),
          write("  :   |    ;      ._.      ; ;   :\n"),
          write("  ;  :    : |    .___.    |   ;  ;\n"),
          write("  :  ;    ;  |   |.-.|   |    : ;`.\n"),
          write("  `-: ,' :   `.  `-'  .'|'-.-;'   |\n"),
          write("      |;-._;__; `.___.'   |       __|___ \n"),
          write("            .:             `.   .'.--|  `.\n").


cara6():- write("                                      ....-----...''      `.\n"),
          write("                                  .';'                     `.\n"),
          write("                                .'  ;                         `.\n"),
          write("                              .'   :                            `.\n"),
          write("                             ;     :                              `.\n"),
          write("                           .'      :                               `.\n"),
          write("                          ;        :                                `.\n"),
          write("                         .         :                                 .\n"),
          write("                        .'          :                                 ;\n"),
          write("                        :           :                                 :\n"),
          write("                       ;            `.   .~--------.._                 ;\n"),
          write("                      ;               ......_   ...  `.`.              `.\n"),
          write("                      .           .' .'      `. `. ; .``.               :\n"),
          write("                     ;          .'; :         `.  .` . `.;              :\n"),
          write("                    ;          .'.';           `.  `. ;.`.`.             :\n"),
          write("                    :        .'  :.'             `. `.`.`.`.             :\n"),
          write("                   :        .'  : :                :   : `.`.            :\n"),
          write("                   :       :    :.'                 `. `. `. `.          `.\n"),
          write("                   :      :     ::                   `. :  `. :           :\n"),
          write("                  : ..    :     ::                    `. :  `. :          :\n"),
          write("                  ::  `.  :    ::                      `.:   `. :         :\n"),
          write("                  ::   : .'    ::-._                    `.:    `:         :\n"),
          write("                  ::   `.:     ::   '-._                _.-----  :        :\n"),
          write("                  ::    `;     :  _.--.._''-.        _.-'..--._  :        :\n"),
          write("                  : :    `     '-'-'(('))|   `     .' |(('))'-'- :        :\n"),
          write("                  : :            `-.`-.-'_|   . .  . |_`-.-'.-'   :      :\n"),
          write("                  : `.              `''''     : :  :   `''''      :      :\n"),
          write("                  `. `.                       . .  .              :      ;\n"),
          write("                   :  `.                      , .  .              :     :\n"),
          write("                    :   `._                   , ;  :              :    ;\n"),
          write("                    :      :                       .              :    :\n"),
          write("                     :      :                .      .             :   :\n"),
          write("                      `.....:               ( _    _ )            :   :\n"),
          write("                             :                 `--'             .';   ;\n"),
          write("                              :                                . ;   :\n"),
          write("                               :              _    _          '  :  .'\n"),
          write("                               :`.        .--'_`'''_'--.    .'   :.'\n"),
          write("                               `.`.        `-._~''~_.-'    .'    '\n"),
          write("                                :  .           `'''      .':\n"),
          write("                                :   `.                  .  :\n"),
          write("                                :     `.              .'   :\n"),
          write("                                :       `-._       _.'     :\n"),
          write("                                :           `-----'        :\n"),
          write("                                ;                          :\n").


cara7():- write("    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n"),
          write("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n"),
          write(" XXXXXXXXXXXXXXXXXX         XXXXXXXX\n"),
          write("XXXXXXXXXXXXXXXX              XXXXXXX\n"),
          write("XXXXXXXXXXXXX                   XXXXX\n"),
          write(" XXX     _________ _________     XXX\n"),
          write("  XX    I  _xxxxx I xxxxx_  I    XX\n"),
          write(" ( X----I         I         I----X )\n"),
          write("( +I    I      00 I 00      I    I+ )\n"),
          write("X( I    I    __0  I  0__    I    I )X\n"),
          write("XX(I    I_________I_________I    I)XX\n"),
          write("XXXI            ( _ )            IXXX\n"),
          write("XXXI                             iXXX\n"),
          write("XXXX|                           |XXXX\n"),
          write("XXXXX|_       _________       |/XXXXX\n"),
          write("XXXXXXX|                     |XXXXXXX\n"),
          write("XXXXXXXX|                   |XXXXXXXX\n"),
          write("XXXXXXXXX|                 |XXXXXXXXXX\n"),
          write("XXXXXXXXXX||______________||XXXXXXXXXX\n").


cara8():- write("          .#########.#######..\n"),
          write("          .#######################.\n"),
          write("        .############################.\n"),
          write("       .################################.\n"),
          write("      .#########,##,#####################.\n"),
          write("     .#########-#,'########## ############.\n"),
          write("    .######'#-##' # ##'### #. `####:#######.\n"),
          write("    #####:'# #'###,##' # # +#. `###:':######\n"),
          write("   .####,'###,##  ###  # # #`#. -####`######.\n"),
          write("  .####+.' ,'#  ##' #   # # #`#`.`#####::####\n"),
          write("  ####'    #  '##'  #   #_'# #.## `#######;##\n"),
          write("  #:##'      '       #   # ``..__# `#######:#\n"),
          write("  #:##'  .#######s.   #.  .s######.\`#####:##\n"),
          write("  #:##   .'______'''    '''_____''. `.#####:#\n"),
          write(" .#:##   ><'(##)'> )    ( <'(##)`><   `####;#\n"),
          write(" ##:##  , , -==-' '.    .` `-==- . |  ######'\n"),
          write(" #|-'| | |      ,  :    : ,       | ` :####:'\n"),
          write(" :#  |: '  '   |  .     .  .  `    `  |`####\n"),
          write(" #|  :|   |   '  '       `  |   . ,   :  #:#\n"),
          write(" #L. | | ,  |   `.-._ _.-.'   .  | |  : ) J##\n"),
          write("###| `  |  '                   |  : : |  /##\n"),
          write(" ## #|.:: '       _    _        ` | | |'####\n"),
          write(" #####||  |  (.-'.__`-'__.`-.)   :| ' ######\n"),
          write(" ######|:      `-...___..-' '     :: |######\n"),
          write(" #######|``.                   ,'|  |#######\n"),
          write(".# ######|  |       ___       | |' |#######\n"),
          write("# #'#####||  |    -     -    |  ,'|### #. #.\n"),
          write("`#  #####| '-.`             ' ,-'  |### #  #\n"),
          write("    #' `#|    '._         ,.-'     |#`#`#.\n"),
          write("         |       .'------' :       |#   #\n"),
          write("         |       :         :       |\n"),
          write("         |       :         :       |\n").


cara9():- write("    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n"),
          write("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n"),
          write(" XXXXXXXXXXXXXXXXXX         XXXXXXXX\n"),
          write("XXXXXXXXXXXXXXXX              XXXXXXX\n"),
          write("XXXXXXXXXXXXX                   XXXXX\n"),
          write(" XXX     _________ _________     XXX\n"),
          write("  XX    I  _xxxxx I xxxxx_  I    XX\n"),
          write(" ( X----I         I         I----X )\n"),
          write("( +I    I      00 I 00      I    I+ )\n"),
          write(" ( I    I    __0  I  0__    I    I )\n"),
          write("  (I    I_________I_________I    I)\n"),
          write("   I           ( ___ )           I\n"),
          write("   I    _                   _    i\n"),
          write("    I    |___           ___|    I\n"),
          write("     I_      |_________|      _I\n"),
          write("       I        |___|        I\n"),
          write("         I                 I\n"),
          write("          |I             I|\n"),
          write("          |  I_________I  |\n").


cara10():-write("   .---------------.     \n"),
          write("   |               |     \n"),
          write("   |               |     \n"),
          write("   |               |     \n"),
          write("   |               |     \n"),
          write("_______________________  \n"),
          write("===========.===========  \n"),
          write(" |  ~~~~~     ~~~~~  |    \n"),
          write(" |      |     |      |   \n"),
          write(" W   ---       ---   W   \n"),
          write(" |.      |o o|      .|   \n"),
          write(" |                   |    \n"),
          write(" V     #########     V    \n"),
          write("  V   ##______/##   V     \n"),
          write("   V ##         ## V      \n"),
          write("    V______v_____V       \n").


cara11():- write("  .---------------. \n"),
          write("   |               | \n"),
          write("   |               | \n"),
          write("   |               | \n"),
          write("   |               | \n"),
          write("_______________________\n"),
          write("===========.===========\n"),
          write(" |  ~~~~~     ~~~~~   | \n"),
          write(" |      |     |       | \n"),
          write(" W   ---       ---    W \n"),
          write(" |.      |o o|       .| \n"),
          write(" |                    | \n"),
          write("  V                  V \n"),
          write("   V     _____/     V \n"),
          write("    V              V \n"),
          write("     V____________V \n").


cara12():- write("    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n"),
           write("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n"),
           write(" XXXXXXXXXXXXXXXXXX         XXXXXXXX\n"),
           write("XXXXXXXXXXXXXXXX              XXXXXXX\n"),
           write("XXXXXXXXXXXXX                   XXXXX\n"),
           write(" XXX     _________ _________     XXX\n"),
           write("  XX    I  _xxxxx I xxxxx_  I    XX\n"),
           write(" ( X----I         I         I----X )\n"),
           write("( +I    I      00 I 00      I    I+ )\n"),
           write(" ( I    I    __0  I  0__    I    I )\n"),
           write("  (I    I________ I_________I    I)\n"),
           write("   I           ( ___ )           I\n"),
           write("   I                             i\n"),
           write("   I                           I\n"),
           write("     I        _________       I\n"),
           write("       I                     I\n"),
           write("         I                 I\n"),
           write("          |I             I|\n"),
           write("          |  I_________I  |\n").

cara13():- write("   .---------------.\n"),
           write("   |               |\n"),
           write("   |               |\n"),
           write("   |               |\n"),
           write("   |               |\n"),
           write("_______________________\n"),
           write("===========.===========\n"),
           write("  | ~~~~~     ~~~~~ |\n"),
           write(" ||     |     |     ||\n"),
           write(" W   ---  | |  ---   W\n"),
           write(" |.      |o o|      .|\n"),
           write("  |                 |\n"),
           write("  |    #########    |\n"),
           write("   |  ## ----- ##  |\n"),
           write("    |##         ##|\n"),
           write("     |_____v_____|\n").


cara14():- write("   .---------------.\n"),
           write("   |       -       |\n"),
           write("   |               |\n"),
           write("   |               |\n"),
           write("   |               |\n"),
           write("_______________________\n"),
           write("===========.===========\n"),
           write(" | ~~~~~     ~~~~~  |\n"),
           write(" |     |     |      |\n"),
           write(" W   ---  | |  ---   W\n"),
           write(" |.      |o o|      .|\n"),
           write("  |                 |\n"),
           write("  |                 |\n"),
           write("   |     _____     |\n"),
           write("    |             |\n"),
           write("     |___________|\n").


cara15():- write("                    dS$$S$S$S$S$S$S$$Sb\n"),
           write("                   :$$S^S$S$S$S$S$S^S$$;\n"),
           write("                   SSP   `^$S$S$^'   TSS\n"),
           write("                   $$       `''       $$\n"),
           write("                  _SS ,-           -  SS_\n"),
           write("                 :-.|  _    - .-   _  |.-;\n"),
           write("                 :|(; ' '-._.'._.-' ` |)|;\n"),
           write("                  \`|  , o       o .  |'/\n"),
           write("                   ':     -'   `-     ;'\n"),
           write("                     ;.              : \n"),
           write("                     : `    ._.    ' ; \n"),
           write("                   .sSb   ._____.   dSs. \n"),
           write("                _.d8dSSb.   ._.   .SSbT8b._ \n"),
           write("            _.oOPd88SSSS T.     .P SSSS888OOo.  \n"),
           write("        _.mMMOOPd888SSSSb TSqqqSP dSSSS88OMOOOMm._\n").


cara16():-  write("      _______\n"),
           write("      |       |\n"),
           write("      | ^   ^ |\n"),
           write("     @ (o) (o) @\n"),
           write("      |   <   |\n"),
           write("      |  ___  |\n"),
           write("      |_______|\n"),
           write("     ____|  |____\n").


cara17():-  write("      _______\n"),
           write("      |       |\n"),
           write("      | ^   ^ |\n"),
           write("     @ (o) (o) @\n"),
           write("      |   <   |\n"),
           write("      | |___| |\n"),
           write("      |_______|\n"),
           write("     ____|  |____\n").

